name: Build and Test on centos7 amd64

on: ["push", "pull_request"]

jobs:
  build-and-test-centos7:
    name: Build and Test on Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull custom centos7 Docker image
        run: |
          docker pull kcllang/kcl-builder:centos7

      - name: Release
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            kcllang/kcl-builder:centos7 \
            source ~/.bash_profile && 
            export PATH=$PATH:/opt/build/bin/ && sed -i 's/llvm12/llvm7/g' kclvm/compiler/Cargo.toml &&
            make && make release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kcl-centos7-amd64
          path: _build/dist/centos/kclvm
