name: Build and Test on MacOS ARCH64
env:
  MACOSX_DEPLOYMENT_TARGET: '10.13'
on: ["push", "pull_request"]
jobs:
  build-and-test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/macos
    # Note: The arch of macos-13-xlarge and macos-14 is arm64
    strategy:
      matrix:
        os: [macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
  
      - name: Install LLVM 18
        run: brew install llvm@18
        shell: bash

      - name: Grammar test
        run: export PATH=$PATH:$PWD/../_build/dist/Darwin/kclvm/bin:/opt/homebrew/opt/llvm@18/bin/ && mlir-translate grid.mlir --mlir-to-llvmir
        shell: bash
