name: build-and-test-macos
on: ["push", "pull_request"]
jobs:
  build-and-test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/macos
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - run: clang --version
      - run: cargo --version
      - run: rustc --print sysroot

      - name: Build KCLVM
        run: make build
        shell: bash
      - name: Grammar test
        run: |
          brew install coreutils
          chmod +x ./internal/scripts/test_grammar.sh
          ./internal/scripts/test_grammar.sh
        shell: bash
      - name: Delete rust cargo
        run: rm -rf /root/.cargo/bin
        shell: bash
      - name: Install LLVM 12
        run: brew install llvm@12
        shell: bash
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.62
          override: true
          components: clippy, rustfmt
      - name: Rust code format check
        working-directory: ./kclvm
        run: cargo fmt --check
        shell: bash
      - name: Rust grammar test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/Darwin/kclvm/bin:/usr/local/opt/llvm@12/bin && make install-rustc-wasm && make && make test-grammar
        shell: bash
      - name: Rust runtime test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/Darwin/kclvm/bin:/usr/local/opt/llvm@12/bin && make install-rustc-wasm && make && make test-runtime
        shell: bash
      - name: Rust unit test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/Darwin/kclvm/bin:/usr/local/opt/llvm@12/bin && make install-rustc-wasm && make && make codecov-lcov
        shell: bash

  build-and-release-kcl-with-plugin:
    # Ref: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-11
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
         submodules: 'true'

      - run: clang --version
      - run: cargo --version
      - run: rustc --print sysroot

      - name: Build CPython
        run: ./internal/scripts/python-plugin/build-cpython.sh
        shell: bash
      - name: Install coreutils
        run: |
          brew install coreutils
        shell: bash
      - name: Delete rust cargo
        run: rm -rf /root/.cargo/bin
        shell: bash
      - name: Install LLVM 12
        run: brew install llvm@12
        shell: bash
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.62
          override: true
          components: clippy, rustfmt

      - name: Build KCL
        run: ./internal/scripts/python-plugin/build-kcl.sh
        shell: bash
      - name: Release
        run: ./internal/scripts/python-plugin/release.sh
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: kclvm-darwin-amd64-with-plugin
          path: _build/kclvm-Darwin-latest.tar.gz
